### ISSUE TITLE
Hidden form fields and basic form field triggering

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#933]
As we collect more complex data with Mapseed, a use case is emerging for the ability to hide certain form fields and trigger their visibility with other fields. For instance, we might have a scenario where selecting the `yes` option from a pair of `yes`-`no` radio buttons reveals a text field that is only relevant when the user has responded `yes` to the radio field.

A feature like opens the door to any number of complex form branching scenarios that are probably not feasible for us right now. To keep the scope in check, I propose we add the most basic version of this feature possible:
* we can declare fields as hidden by default
* we can declare other fields as "trigger" fields, and we can list which fields are triggered and which value triggers them.

So, a sample config footprint might look like this:

```
fields:
  - name: dog_owner
    type: big_radio
    prompt: _(Do you own a dog?)
    content:
      - label: _(Yes)
        value: yes
      - label: _(No)
        value: no
    trigger:
      trigger_value: yes
      fields:
        - dog_name
        - dog_age
  - name: dog_name
    type: text
    prompt: _(My dog's name is:)
    hidden_default: true
  - name: dog_age
    type: text
    prompt: _(My dog's age is:)
    hidden_default: true
```
